// bits/stdc++.h

#include <iostream>
#include <vector>
#include <string>
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cstdio>
#include <cstdarg>
#include <map>
#include <set>
#include <stack>
#include <queue>
#include <deque>
#include <utility>
#include <bitset>
#include <list>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <complex>
#include <functional>
#include <numeric>
#include <iterator>
#include <valarray>
#include <climits>
#include <cctype>
#include <cassert>
#include <cerrno>
#include <cfloat>
#include <ciso646>
#include <climits>
#include <clocale>
#include <cstdalign>
#include <cstdbool>
#include <cstdint>
#include <ctgmath>
#include <cwchar>
#include <cwctype>
//#include <cxxabi.h>
//#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <fenv.h>
#include <float.h>
#include <inttypes.h>
#include <limits.h>
#include <locale.h>
#include <math.h>
#include <memory.h>
//#include <pthread.h>
//#include <sched.h>
//#include <semaphore.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
//#include <sys/wait.h>
#include <time.h>
//#include <unistd.h>
#include <wchar.h>
#include <wctype.h>
